import type { NextPage } from "next";
import Head from "next/head";
import { Card } from "../components/Card";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import styles from "../styles/Home/styles.module.scss";

const CARDS = [
  <Card
    key="1"
    id={1}
    title="CARD TITLE 1"
    description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In hac habitasse platea dictumst."
  />,
  <Card
    key="2"
    id={2}
    title="CARD TITLE 2"
    description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In hac habitasse platea dictumst."
  />,
  <Card
    key="3"
    id={3}
    title="CARD TITLE 3"
    description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In hac habitasse platea dictumst."
  />,
];

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>{CARDS}</main>

      <Footer />
    </>
  );
};

export default HomePage;
